### ISSUE TITLE
Parks

### ISSUE THREAD

**Issue by jayvdb** [honzaap/GithubCity#18]
When adjoining days with zero contribs are surrounded by towers, I think those 0 contrib days should be merged together to create larger park-land sections, as it typically means the user went on holidays.

This merging into park-land wont make sense for the part of the year which is still in the future.  Perhaps some building equipment could be put on the future few weeks, to indicate those weeks are "under construction", and then park-land for future weeks ahead of that.

**Comment by honzaap** [comment]
I currently have no plan of adding new features. Thanks for the idea, maybe in the future.

**Comment by arpitBhalla** [comment]
Feature Request: roads between buildings.

**Comment by honzaap** [comment]
?

**Comment by arpitBhalla** [comment]
May be in future 🫠 but roads and cars on road would look nice.

**Comment by honzaap** [comment]
Im pretty sure that there are roads already.

**Comment by gurpreetkaits** [comment]
Vr city of Github Great!

**Comment by ctsstc** [comment]
Sharks with laz0r beams attached to their heads plz; kthnxbie < 3

**Comment by sandeep661** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @lomartins, @Texhnolyze47, @hhuseyinpay, @benji6, @S7venLights, @Ac0rnz, @jbuisine, @GentlemanMC, @heroslender, @happygong, @lidangzzz, @TIT8, @dddsssl, @HZongLin, @loganynguyen, @afro-cloud, @mtlbrownsugar, @dedouwe26, @Vyvy-vi, @ruthiel, @IAMAGeeker, @LuckysHere, @ismailkhan-dev, @JingkunLiu, @Sangeppato, @22yeetz22, @1fahh, @gumdropsteve, @HananoshikaYomaru, @nserrano199, @Fern1ck, @aeyno, @noxonsu, @shimonosatoru, @balance-wtf, @Rookiewan, @prajwalpathak, @johnLitoBardinas, @Aman9das, @VCStardust, @mnnkhndlwl, @Zeczero, @cwmke, @ngocanhtve, @brndnsvr, @samirelanduk, @KNipunDananjaya, @miquelrossello, @kellyjoe256, @cyd1310997
