### ISSUE TITLE
docs: add issue template 

### ISSUE THREAD

**Issue by SuperAayush** [honzaap/GithubCity#19]
With issue forms, you can create issue templates that have customizable web form fields. You can encourage contributors to include specific, structured information by using issue forms in your repository. Issue forms are written in YAML using the GitHub form schema.

For more information read this documentation -> https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by honzaap** [comment]
idc
