### ISSUE TITLE
500 when generating my profile

### ISSUE THREAD

**Issue by SuperSandro2000** [honzaap/GithubCity#23]
When trying to generate my profile I receive a 500 from https://uvdvlzzjiciqsfkl7u37nnhnsm0sleur.lambda-url.eu-central-1.on.aws/?username=SuperSandro2000&year=2022

**Comment by honzaap** [comment]
It works just fine for me, the link to AWS lambda does return 500 but the app works... weird. Does this also throw an error? https://honzaap.github.io/GithubCity/?name=SuperSandro2000&year=2022

**Comment by SuperSandro2000** [comment]
Now it works. Before I received an error if maybe my username was wrong.
