### ISSUE TITLE
Enter username doesn't work

### ISSUE THREAD

**Issue by PunGrumpy** [honzaap/GithubCity#24]
When I filled username, my username is disappeared ,my 3d contribution doesn't appear and still homepage.

**Comment by PunGrumpy** [comment]
When I enter website like this
![image](https://user-images.githubusercontent.com/108584943/193070612-59f2c720-77fa-4157-abd2-246a62667966.png)

**Comment by honzaap** [comment]
Are there some error messages in the console? What browser are you on?

**Comment by PunGrumpy** [comment]
I use chrome but I try min browser it available

**Comment by PunGrumpy** [comment]
This error messages
![image](https://user-images.githubusercontent.com/108584943/193079145-cf140385-3528-4568-a25e-73061a4f90da.png)

**Comment by honzaap** [comment]
It could be something related to your GPU as stated in [this stackoverflow thread](https://stackoverflow.com/questions/54232528/error-creating-webgl-context-three-js-chrome). If that is the case, there is nothing I can do.

Opening devtools and refreshing apparently fixes this issue, you could try it.

**Comment by PunGrumpy** [comment]
Ok, thank you
