### ISSUE TITLE
Crashing The Whole Browser!

### ISSUE THREAD

**Issue by Quicksilver-lab** [honzaap/GithubCity#25]
I'm trying to Generate the 3D model for my Contributions Graph @Quicksilver-lab and it crashes the whole browser and due to this i have lost my unsaved work!

**Comment by honzaap** [comment]
There is a lot to load and the way these models are rendered is pretty bad, sorry for that

**Comment by Quicksilver-lab** [comment]
> There is a lot to load and the way these models are rendered is pretty bad, sorry for that

Yah Because it uses local storage of the browser Right??

![image](https://github.com/user-attachments/assets/65c25f01-3b94-4578-805b-1041fcd28daf)

**Comment by honzaap** [comment]
it doesn't save anything into localStorage, it's just that every single floor is handled as a separate object that is being loaded one by one instead of doing something more efficient like instancing, in your scene there are probably ~10000 objects. The code is kinda shit to be honest

**Comment by Quicksilver-lab** [comment]
> it doesn't save anything into localStorage, it's just that every single floor is handled as a separate object that is being loaded one by one instead of doing something more efficient like instancing, in your scene there are probably ~10000 objects. The code is kinda shit to be honest

Yah and i kinda like your this shit to be honest 😆
