### ISSUE TITLE
Allow downloading of City models

### ISSUE THREAD

**Issue by jewlexx** [honzaap/GithubCity#6]
Allow the downloading of City 3D models, similar to how [Github Skylines](https://skyline.github.com/) does.

I am not sure how complicated this would be though I haven't really dealt with javascript 3D models in the past, so I am not sure what this would require.

**Comment by honzaap** [comment]
That is a good idea, I'll see what I can do.

**Comment by eggplants** [comment]
Ref: https://stackoverflow.com/questions/48072408

Put:
```html
<a id="dl" />
```

And:
```js
const sceneToStlBlobUrl = (scene) => {
  const exporter = new THREE.STLExporter();
  const str = exporter.parse(scene);
  var blob = new Blob([str], {type: 'text/plain'});
  return URL.createObjectURL(blob)
}

/// ...

const dl = document.getElementById("dl")
dl.href = sceneToStlBlobUrl(scene);
dl.download = `${name}-${year}-city.stl`;
```

**Comment by honzaap** [comment]
Thanks for the tip, I'll try to add it tomorrow.

**Comment by eggplants** [comment]
If you don't mind, could I contribute it?

**Comment by honzaap** [comment]
Sure, why not, you can add a button to the right like the AutoRotate option
